version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
      
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: "postgres"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
  
  reservationapp:
    build:
      context: ReservationApp
    depends_on:
      - postgres
    ports:
      - "8070:8070"
  paymentapp:
    build:
      context: PaymentApp
    depends_on:
      - postgres
    ports:
      - "8060:8060"
  loyaltyapp:
    build:
      context: LoyaltyApp
    depends_on:
      - postgres
    ports:
      - "8050:8050"
  gateway:
    build:
      context: Gateway
    ports:
      - "8080:8080"
    depends_on:
      - reservationapp
      - paymentapp
      - loyaltyapp


volumes:
  db-data: